const Destination = require("../models/Destination");
const groqService = require("../services/groqService");

exports.getDestination = async (req, res) => {
  try {
    const destinationParam = req.params.destination;

    if (!destinationParam) {
      return res.status(400).json({
        message: "Destination is required",
      });
    }

    const destinationName =
      decodeURIComponent(destinationParam).trim();

    if (!destinationName) {
      return res.status(400).json({
        message: "Destination is required",
      });
    }

    console.log(
      `Exploring destination: ${destinationName}`
    );

    // -----------------------------------------
    // 1. Check MongoDB first (case insensitive)
    // -----------------------------------------

    const existingDestination =
      await Destination.findOne({
        destination: {
          $regex: `^${destinationName}$`,
          $options: "i",
        },
      });

    if (existingDestination) {
      console.log(
        `Using cached destination: ${existingDestination.destination}`
      );

      return res.json(existingDestination);
    }

    // -----------------------------------------
    // 2. Not found → Generate using Groq
    // -----------------------------------------

    console.log(
      `Generating ${destinationName} using Groq...`
    );

    const generatedDestination =
      await groqService.generateDestination(
        destinationName
      );

    // -----------------------------------------
    // 3. Check again before creating
    // -----------------------------------------
    // This protects against two requests arriving
    // at almost the same time.

    const existingAfterGeneration =
      await Destination.findOne({
        destination: {
          $regex: `^${generatedDestination.destination}$`,
          $options: "i",
        },
      });

    if (existingAfterGeneration) {
      console.log(
        `Destination already generated by another request. Using existing data.`
      );

      return res.json(existingAfterGeneration);
    }

    // -----------------------------------------
    // 4. Save to MongoDB
    // -----------------------------------------

    const newDestination =
      await Destination.create(
        generatedDestination
      );

    console.log(
      `Saved new destination: ${newDestination.destination}`
    );

    // -----------------------------------------
    // 5. Return destination
    // -----------------------------------------

    return res.status(200).json(
      newDestination
    );

  } catch (error) {

    console.error(
      "Explore destination error:",
      error
    );

    // -----------------------------------------
    // Handle duplicate key race condition
    // -----------------------------------------

    if (error.code === 11000) {

      const existingDestination =
        await Destination.findOne({
          destination: {
            $regex: `^${req.params.destination}$`,
            $options: "i",
          },
        });

      if (existingDestination) {
        return res.json(existingDestination);
      }
    }

    return res.status(500).json({
      message: "Failed to load destination",
      error: error.message,
    });
  }
};